# Site Settings
#
title: Urdu Website
subtitle: Information about Urdu authors and books.
baseurl: /test-jekyll

# Comment both lines below to render in English. Uncomment for Urdu.
# lang: ur
# dir: rtl

# RSS Feed config
description: Information about Urdu authors and books.

# Google Analytics
# google_analytics_tracking_id: UA-xxxxxxxx-x

#
# Jekyll Settings
#
collections:
  author:
    output: true
    permalink: /authors/:path/
  book:
    output: true
    permalink: /books/:path/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
